### ISSUE TITLE
Icon Selection screen is completely white on Umbraco 7.5.11

### ISSUE THREAD

**Issue by blachawk** [harvzor/iconator#4]
I followed your directions in the installation process, but when I go to actually select an icon on a content page in Umbraco, the side page that suppose to display all the icons, is completely white.   I went into developer tools, inspected the page, and can see that all the HTML for each icon is there, but for some reason the icons themselves are invisible.  

**Here is what I am seeing:**

- I added font-awesome to my /css/ file location under umbraco
- my font mime types are approved in IIS
- My paths to my font-awesome fonts looks like this....
        src: url('/../css/fonts/fontawesome-webfont.eot?v=4.7.0');
- No path errors in my console tab in developer tools

![missing-icons](https://cloud.githubusercontent.com/assets/3985279/24221368/73ef62be-0f24-11e7-922b-9b0fec6b73f7.png)
I'm out of ideas on why its white.  What should I check next?

**Comment by harvzor** [comment]
Hi I'm on holiday right now but I'll try and help you along!

Can you send a screen shot of the settings you entered for the property type?

**Comment by harvzor** [comment]
I think perhaps the path in the CSS file which points to the font file is incorrect.

'url('/../css/fonts/fontawesome-webfont.eot?v=4.7.0');' doesn't make any sense to me as it is saying; go to the root of the website, then go back one, then go to '/css/fonts/fontawesome-webfont.eot'.

I think this path should actually be 'url('/css/fonts/fontawesome-webfont.eot?v=4.7.0');', assuming that at the root of the website, the fonts are stored in a fonts folder which is in the css folder.

Hope this makes sense!

Can I also check that you have managed to get the font icons to render properly on the front end of the website (as in outside of the Umbraco back office)? If you can get it to render there but not in Umbraco, then we know it's an issue with either your setup or my package. :)

**Comment by harvzor** [comment]
I have tested again on Umbraco 7.5.11 with font awesome 7.4.2 and it's working just fine.

I think this was an error with your setup.

Closing.
