### ISSUE TITLE
Is this still being mantained?

### ISSUE THREAD

**Issue by simoneldevig** [harvzor/iconator#7]
Is this package still being maintained @HarveyWilliams? 

In relation to my latest PR #6 I would like to hear if this package is still maintained since I'm currently using my fork in production projects. 

If you don't have time to maintain it I would gladly help with that - just let me know :-)

**Comment by bgunnarsson** [comment]
Same here, I've made a lot of changes to fit my need and incorporated the login this PR fixed. I will gladly commit those changes here but if @HarveyWilliams isn't still maintaining this then I don't see the point in doing so..

**Comment by harvzor** [comment]
Sorry about the lack of support on this package. I'm finally working on some small improvements.

Please submit any new pull requests and I might be able to merge them to create a new release.

If either of you are interested in becoming a collaborator with control over the repo, I will gladly add you. 

I'm not sure of my future with Umbraco as I'm moving away from the standard .NET stack (but I'm interested in .Net Core). Perhaps I should even give the whole repo away?

Let me know your thoughts!

**Comment by ahwm** [comment]
I just made this editor work on Umbraco 8 - https://github.com/ahwm/iconator/tree/umbraco8

**Comment by harvzor** [comment]
@ahwm Thanks. I've made a pull request which I'll review: https://github.com/Harvzor/iconator/pull/9

**Comment by simoneldevig** [comment]
Closing since this is obviously still being maintained :)

**Comment by harvzor** [comment]
Merged the Umbraco8.0 fix to my own branch called Umbraco8.0.

Created a new issue to trach progress: https://github.com/Harvzor/iconator/issues/11
